# espanso match file
matches:
  # Simple text replacement
  - trigger: "..lex"
    replace: '/label ~"devops::create" ~"group::ide" ~"VS Code" ~"Category:Editor Extension" ~"section::dev"'
  - trigger: "..lf"
    replace: '/label ~"type::feature"'
  - trigger: "..lb"
    replace: '/label ~"type::bug"'
  - trigger: "..lm"
    replace: '/label ~"type::maintenance"'
  - trigger: "..thx"
    replace: 'Thank you for creating this issue :pray:'
  # Common spelling mistakes
  - trigger: "lenght"
    replace: 'length'
    # propagate_case: true
    # word: true
  - trigger: "..shrug"
    replace: "¯\\_(ツ)_/¯"
