# espanso match file
matches:
  # Simple text replacement
  - trigger: "..lex"
    replace: '/label ~"devops::ai-powered" ~"group::editor extensions" ~"VS Code" ~"Category:Editor Extensions" ~"section::dev" ~"Editor Extensions::VS Code"'
  - trigger: "..lls"
    replace: '/label ~"devops::ai-powered" ~"group::editor extensions" ~"VS Code" ~"Category:Editor Extensions" ~"section::dev" ~"Editor Extensions::Language Server"'
  - trigger: '..lteam'
    replace: '/label ~"devops::ai-powered" ~"group::editor extensions" ~"Category:Editor Extensions" ~"section::dev"'
  - trigger: "..lf"
    replace: '/label ~"type::feature"'
  - trigger: "..lb"
    replace: '/label ~"type::bug"'
  - trigger: "..lm"
    replace: '/label ~"type::maintenance"'
  - trigger: "..thx"
    replace: 'Thank you for creating this issue :pray:'
  - trigger: "..p1"
    replace: '🔴'
  - trigger: "..p2"
    replace: '🟠'
  - trigger: "..p3"
    replace: '🟡'
  - trigger: "..p4"
    replace: '🟢'
  - trigger: "..kbd"
    replace: '<kbd></kbd>'
  - trigger: "..tl"
    replace: '- [ ] '
  # Common spelling mistakes
  - trigger: "lenght"
    replace: 'length'
  - trigger: "taht"
    replace: 'that'
    # propagate_case: true
    # word: true
  - trigger: "..shrug"
    replace: "¯\\_(ツ)_/¯"
  - trigger: "..approve"
    replace: "/approve\n\n/unassign_reviewer @viktomas \n\n/assign_reviewer \n\n can I please ask you to do a ~frontend maintainer review for this MR? :pray:\n"
  - trigger: "..fr"
    replace: "\n\n---\n _Help me improve my MR reviews. [Give me feedback](https://forms.gle/3UfFQBbGs28rP5Pz7). All answers are optional, it can take as little as 20s._\n"
  - trigger: "VSE"
    replace: "VS Code Extension"
  - trigger: "..parrots"
    replace: ":parrot-wave-1::parrot-wave-2::parrot-wave-3::parrot-wave-4::parrot-wave-5::parrot-wave-6::parrot-wave-7::parrot-wave-8::parrot-wave-9:"
  - trigger: "..multiroot"
    replace: "[Multiroot Workspaces](https://code.visualstudio.com/docs/editing/workspaces/workspaces#_multiroot-workspaces)"
